# This rule tells Netlify to proxy all requests starting with /api
# to your EC2 server.

[[redirects]]
  from = "/api/*"
  to = "https://np8fl1g1xc.execute-api.ap-south-1.amazonaws.com/prod/:splat"
  status = 200
  force = true